trigger: none # Este pipeline no se dispara por commits, sino por el CI

resources:
  pipelines:
    - pipeline: ci-pipeline # Alias interno para el recurso
      source: 'flyblue-ci-pipeline-gh'
      trigger:
        branches: # Se dispara cuando el CI termine en cualquiera de estas ramas
          include:
            - dev   # <-- CORRECCIÓN 1 (era 'develop')
            - test
            - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageRepository: 'daldeoscoder/flyblue-api' # El repo de Docker

stages:

  # ==========================================
  # ETAPA 1: DESPLIEGUE A "DEV"
  # ==========================================
  - stage: Deploy_Dev
    displayName: 'Deploy to DEVELOPMENT'
    dependsOn: [] # Se ejecuta tan pronto como el CI termina

    # --- CONDICIÓN: Solo se ejecuta si la rama que disparó el CI fue 'dev' ---
    condition: eq(variables['Build.SourceBranchName'], 'dev') # <-- CORRECCIÓN 2 (era 'develop')

    jobs:
      - deployment: DeployDev
        environment: 'Development' # <-- Nombre del entorno gráfico en DevOps
        variables:
          - group: 'VG-FLYBLUE-DEV' # Carga los secretos para DEV
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureCLI@2
                  displayName: 'Set DEV Env Variables & Restart'
                  inputs:
                    azureSubscription: 'SC-ARM-FLYBLUE-DEV' # Service Connection directa
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      az webapp config appsettings set -n 'flyblue-api-server-dev' -g 'RG-FLYBLUE-DEV' --settings DATABASE_URL="$(DATABASE_URL)" WEBSITES_PORT="8000"
                      az webapp restart -n 'flyblue-api-server-dev' -g 'RG-FLYBLUE-DEV'

                - task: AzureWebAppContainer@1
                  displayName: 'Deploy Container to DEV Web App'
                  inputs:
                    azureSubscription: 'SC-ARM-FLYBLUE-DEV' # Service Connection directa
                    appName: 'flyblue-api-server-dev'
                    # --- Despliega la imagen etiquetada como "dev" ---
                    containers: '$(imageRepository):dev' # <-- CORRECCIÓN 3 (era 'develop')

  # ==========================================
  # ETAPA 2: DESPLIEGUE A "TEST" (Esta etapa estaba BIEN)
  # ==========================================
  - stage: Deploy_Test
    displayName: 'Deploy to TESTING'
    dependsOn: []

    # --- CONDICIÓN: Solo se ejecuta si la rama fue 'test' ---
    condition: eq(variables['Build.SourceBranchName'], 'test')

    jobs:
      - deployment: DeployTest
        environment: 'Testing' # Entorno gráfico de DevOps
        variables:
          - group: 'VG-FLYBLUE-TEST' # Carga los secretos para TEST
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureCLI@2
                  displayName: 'Set TEST Env Variables & Restart'
                  inputs:
                    azureSubscription: 'SC-ARM-FLYBLUE-TEST' # Service Connection directa
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      az webapp config appsettings set -n 'flyblue-api-server-test' -g 'RG-FLYBLUE-TEST' --settings DATABASE_URL="$(DATABASE_URL)" WEBSITES_PORT="8000"
                      az webapp restart -n 'flyblue-api-server-test' -g 'RG-FLYBLUE-TEST'

                - task: AzureWebAppContainer@1
                  displayName: 'Deploy Container to TEST Web App'
                  inputs:
                    azureSubscription: 'SC-ARM-FLYBLUE-TEST' # Service Connection directa
                    appName: 'flyblue-api-server-test'
                    containers: '$(imageRepository):test'

  # ==========================================
  # ETAPA 3: DESPLIEGUE A "PROD" (Esta etapa estaba BIEN)
  # ==========================================
  - stage: Deploy_Prod
    displayName: 'Deploy to PRODUCTION'
    dependsOn: []

    # --- CONDICIÓN: Solo se ejecuta si la rama fue 'main' ---
    condition: eq(variables['Build.SourceBranchName'], 'main')

    jobs:
      - deployment: DeployProd
        environment: 'Production' # <-- Aquí se configura la Aprobación Manual en la GUI
        variables:
          - group: 'VG-FLYBLUE-MAIN' # Carga los secretos para PROD
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureCLI@2
                  displayName: 'Set PROD Env Variables & Restart'
                  inputs:
                    azureSubscription: 'SC-ARM-FLYBLUE-MAIN' # Service Connection directa
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      az webapp config appsettings set -n 'flyblue-api-server-main' -g 'RG-FLYBLUE-MAIN' --settings DATABASE_URL="$(DATABASE_URL)" WEBSITES_PORT="8000"
                      az webapp restart -n 'flyblue-api-server-main' -g 'RG-FLYBLUE-MAIN'

                - task: AzureWebAppContainer@1
                  displayName: 'Deploy Container to PROD Web App'
                  inputs:
                    azureSubscription: 'SC-ARM-FLYBLUE-MAIN' # Service Connection directa
                    appName: 'flyblue-api-server-main'
                    containers: '$(imageRepository):main'