trigger:
  branches:
    include:
      - dev     # Rama para Dev
      - test    # Rama para Test
      - main    # Rama para Prod

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Uso de la Service Connection de Docker que creada para Dev
  dockerRegistryServiceConnection: 'SC-DR-FLYBLUE-DEV'
  imageRepository: 'daldeoscoder/flyblue-api' # repo en Docker Hub
  containerRegistry: 'index.docker.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)' # Tag único (ej: 1234)

stages:
  - stage: Build
    displayName: Build and push stage
    jobs:
      - job: Build
        displayName: Build Docker Image
        steps:
          - task: Docker@2
            displayName: Build and push Docker image
            inputs:
              command: buildAndPush
              repository: $(imageRepository)
              dockerfile: $(dockerfilePath)
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(tag)
                $(Build.SourceBranchName)
                
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Build Info'
            inputs:
              PathtoPublish: '$(Build.SourcesDirectory)'
              ArtifactName: 'source-code'